{{- range $index, $service := .Values.models }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-embedding-{{ lower $index }}
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}-embedding-{{ lower $index }}
    app.kubernetes.io/instance: {{ $.Release.Name }}{{ lower $index }}
spec:
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Release.Name }}-embedding-{{ lower $index}}
      app.kubernetes.io/instance: {{ $.Release.Name }}{{ lower $index }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Release.Name }}-embedding-{{ lower $index }}
        app.kubernetes.io/instance: {{ $.Release.Name }}{{ lower $index}}
    spec:
      imagePullSecrets:
        - name: {{ $.Release.Name }}-embeddings-pull-secret
      containers:
        - name: {{ $.Release.Name }}-embedding-{{ lower $index }}
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
          {{- if eq $service.machineFamily "g5" }}
          image: trieve/embeddings:g5
          {{- else if eq $service.machineFamily "g4dn" }}
          image: trieve/embeddings:g4dn
          {{- else }}
          image: trieve/embeddings:g4dn
          {{- end }}
          args: 
            - "--model-id" 
            - {{ $service.modelName | quote }}
            {{- if $service.isSplade }}
            - "--pooling"
            - "splade"
            {{- end }}
            {{- if $service.revision }}
            - --revision
            - {{ $service.revision | quote }}
            {{- end }}
            {{- if $service.hfToken }}
            - --hf-api-token
            - {{ $service.hfToken | quote }}
            {{- end }}
          ports:
            - containerPort: 80
          resources:
            limits:
              nvidia.com/gpu: 1
{{- end }}
