{{- range $index, $service := .Values.models }}
---
{{- if $service.serviceMonitor }}
{{- if $service.serviceMonitor.enabled | default false }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Release.Name }}-generation-{{ lower $index }}-monitor
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: svc
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Release.Name }}-generation-{{ lower $index }}-service
      app.kubernetes.io/instance: {{ $.Release.Name }}{{ $index }}
{{- end }}
{{- end }}
{{- end }}
