apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-backend-config
  namespace: default
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: false
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: always-ssl-frontend-config
  namespace: default
spec:
  redirectToHttps:
    enabled: true
