apiVersion: v1
kind: ConfigMap
metadata:
  name: trieve-server-config
data:
  SENTRY_URL: "https://81fadb6c2761da92de2a9a6f919fe66d@sentry.withtrieve.com/4"
  ADMIN_API_KEY: {{ .Values.config.trieve.adminApiKey }}
  BASE_SERVER_URL: {{ .Values.config.trieve.baseServerUrl }}
  REDIS_URL: {{ .Values.config.redis.uri }}
  QDRANT_URL: {{ .Values.config.qdrant.qdrantUrl }}
  QDRANT_API_KEY: {{ .Values.config.qdrant.apiKey }}
  QUANTIZE_VECTORS: {{ .Values.config.qdrant.quantizeVectors | quote }}
  QDRANT_SHARD_COUNT: {{ .Values.config.qdrant.shardCount | quote }}
  REPLICATION_FACTOR: {{ .Values.config.qdrant.replicationFactor | quote }}
  VECTOR_SIZES: {{ join "," .Values.config.qdrant.vectorSizes | quote }}
  DATABASE_URL: {{ .Values.postgres.dbURI }}
  SMTP_RELAY: {{ .Values.config.smtp.relay }}
  SMTP_USERNAME: {{ .Values.config.smtp.username }}
  SMTP_PASSWORD: {{ .Values.config.smtp.password }}
  SMTP_EMAIL_ADDRESS: {{ .Values.config.smtp.emailAddress }}
  OPENAI_API_KEY: {{ .Values.config.openai.apiKey }}
  LLM_API_KEY: {{ .Values.config.llm.apiKey }}
  SECRET_KEY: {{ .Values.config.trieve.secretKey | quote }}
  SALT: {{ .Values.config.trieve.salt }}
  S3_ENDPOINT: {{ .Values.config.s3.endpoint }}
  S3_ACCESS_KEY: {{ .Values.config.s3.accessKey }}
  S3_SECRET_KEY: {{ .Values.config.s3.secretKey }}
  S3_BUCKET: {{ .Values.config.s3.bucket }}
  COOKIE_SECURE: {{ .Values.config.trieve.cookieSecure | quote }}
  QDRANT_COLLECTION: {{ .Values.config.qdrant.collection }}
  TIKA_URL: tika.default.svc.cluster.local
  OPENAI_BASE_URL: {{ .Values.config.openai.baseUrl }}
  STRIPE_SECRET: {{ .Values.config.stripe.secret }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.config.stripe.webhookSecret }}
  ADMIN_DASHBOARD_URL: {{ .Values.config.vite.dashboardUrl }}
  OIDC_CLIENT_SECRET: {{ .Values.config.oidc.clientSecret }}
  OIDC_CLIENT_ID: {{ .Values.config.oidc.clientId }}
  OIDC_AUTH_REDIRECT_URL: {{ .Values.config.oidc.authRedirectUrl }}
  OIDC_ISSUER_URL: {{ .Values.config.oidc.issuerUrl }}
  GPU_SERVER_ORIGIN: {{ .Values.config.trieve.gpuServerOrigin }}
  SPARSE_SERVER_QUERY_ORIGIN: {{ .Values.config.trieve.sparseServerQueryOrigin }}
  SPARSE_SERVER_DOC_ORIGIN: {{ .Values.config.trieve.sparseServerDocOrigin }}
  EMBEDDING_SERVER_ORIGIN: {{ .Values.config.trieve.embeddingServerOrigin }}
  EMBEDDING_SERVER_ORIGIN_BGEM3: {{ .Values.config.trieve.embeddingServerOriginBGEM3 }}
  EMBEDDING_SERVER_ORIGIN_JINA_CODE: {{ .Values.config.trieve.embeddingServerOriginJinaCode }}
  JINA_CODE_API_KEY: {{ .Values.config.trieve.jinaCodeApiKey }}
  RERANKER_SERVER_ORIGIN: {{ .Values.config.trieve.rerankerServerOrigin }}
  UNLIMITED: {{ .Values.config.trieve.unlimited | quote }}
  REDIS_CONNECTIONS: "30"
  AWS_REGION: {{ .Values.config.s3.region }}
  CLICKHOUSE_URL: {{ .Values.config.analytics.clickhouseUrl | quote }}
  CLICKHOUSE_DB: {{ .Values.config.analytics.clickhouseDB | quote }}
  CLICKHOUSE_USER: {{ .Values.config.analytics.clickhouseUser | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.config.analytics.clickhousePassword | quote }}
  USE_ANALYTICS: {{ .Values.config.analytics.enabled | quote }}
  BM25_ACTIVE: {{ .Values.config.trieve.bm25Active | quote }}
  SUBTRACE_TOKEN: {{ .Values.config.trieve.subtraceToken | quote }}
