{{- $name := "chat-service" }}
{{- $selector := "chat" }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  # annotations:
  #   beta.cloud.google.com/backend-config: '{"ports": {"80":"frontend-backend-config"}}'
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      name: chat
  selector:
    app.kubernetes.io/name: {{ $selector }}
    app.kubernetes.io/instance: trieve
