apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-worker
  labels:
    app.kubernetes.io/name: delete-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: delete-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: delete-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: delete-worker
        image: {{ printf "%s%s:%s" (ternary "trieve/" "localhost:5000/" (ne .Values.environment "local")) "delete_worker" .Values.containers.delete_worker.tag }}
        envFrom:
          - configMapRef:
              name: trieve-server-config
        env:
          - name: DELETE_CHUNK_BATCH_SIZE
            value: {{ .Values.config.delete_worker.batch_size | quote }}
