apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  labels:
    app.kubernetes.io/name: ingest
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: ingest
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingest
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: ingest
        image: {{ printf "%s:%s" "trieve/ingest" .Values.containers.ingest.tag }}
        envFrom:
          - configMapRef:
              name: trieve-server-config
