apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app.kubernetes.io/name: search
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"frontend-backend-config"}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: search
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: search
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: search
        livenessProbe:
          httpGet:
            path: "/"
            port: 80
        readinessProbe:
          httpGet:
            path: "/"
            port: 80
        image: {{ printf "%s:%s" "trieve/search" $.Values.containers.search.tag }}
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: trieve-frontend-config
