{{- $name := "search-service" }}
{{- $selector := "search" }}
kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  # annotations:
  #   cloud.google.com/backend-config: '{"ports": {"80":"frontend-backend-config"}}'
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 80
      protocol: TCP
      name: search
  selector:
    app.kubernetes.io/name: {{ $selector }}
    app.kubernetes.io/instance: trieve
