apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-qdrant
  labels:
    app.kubernetes.io/name: sync-qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 0 # Set to 0 by default
  selector:
    matchLabels:
      app.kubernetes.io/name: sync-qdrant
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sync-qdrant
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.gcloud.serviceAccountName }}
      containers:
      - name: sync-qdrant
        image: {{ printf "%s:%s" "trieve/sync_qdrant" .Values.containers.sync_qdrant.tag }}
        envFrom:
          - configMapRef:
              name: trieve-server-config
