apiVersion: batch/v1
kind: CronJob
metadata:
  name: word-id-cronjob
  labels:
    app.kubernetes.io/name: word-id-cronjob
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.gcloud.serviceAccountName }}
          restartPolicy: OnFailure
          containers:
          - name: set-ids-job
            image: {{ printf "%s:%s" "trieve/word-id-cronjob" .Values.containers.word_id_cronjob.tag }}
            envFrom:
              - configMapRef:
                  name: trieve-server-config
